version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: algolia/algoliasearch-client-php
    versions:
    - 2.7.3
    - 2.8.0
    - 3.0.0
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
